modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/CreeperHost/ResourcefulCreepers/issues"
license = "BSD 4-Clause License"

[[mods]]
modId = "resourcefulcreepers"
version = "${version}"
displayName = "Resourceful Creepers"
authors = "CreeperHost"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.resourcefulcreepers]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "polylib"
mandatory = true
versionRange = "[1200.0.3,)"
ordering = "AFTER"
side = "BOTH"
