modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CreeperHost/ResourcefulCreepers/issues"
license = "BSD 4-Clause License"

[[mods]]
modId = "resourcefulcreepers"
version = "${version}"
displayName = "Resourceful Creepers"
authors = "CreeperHost"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.resourcefulcreepers]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "polylib"
mandatory = true
versionRange = "[2004.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "resourcefulcreepers.mixins.json"
